language: node_js
node_js:
  - "stable"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master

    # 55f2a7e2affca08250fa3ac2f48ebcfd0b8e5d9f